CREATE TABLE product(productid INTEGER NOT NULL,name VARCHAR(100) NOT NULL, categoryid INTEGER, PRIMARY KEY (categoryid));
CREATE TABLE category(categoryid INTEGER NOT NULL,name VARCHAR(100) NOT NULL, PRIMARY KEY (id));
